#!/usr/bin/env python3


# exersise 2-1
# how many seconds are there in 42 minutes and 42 seconds?

print(42 * 60 + 42)

'''
    42 minutes and 42 seconds is 40 * 60 + 42, as there are 60 seconds in each minute, or 2562 seconds
    the python interpreter will follow the normal order of operations,
    however sometimes using extra parenthesis is just easier to keep track of
    print((42 * 60) + 42)
'''
